CodeFirst/Models/Cipher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CodeFirst.Models
{
    public class Cipher
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CipherId { get; set; }
        public string OldChar { get; set; }
        public string NewChar { get; set; }
    }
}

CodeFirst/Models/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CodeFirst.Models
{
    public class Message
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MessageId { get; set; }
        public string Text { get; set; }
        public DateTime ReceiptTime { get; set; }
    }
}

CodeFirst/Controllers/CipherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Http;
using CodeFirst.DAL;
using CodeFirst.Models;

namespace CodeFirst.Controllers
{
    public class CipherController : ApiController
    {
        private CipherContext ctx;

        public CipherController()
        {
            ctx = new CipherContext();
        }

        [Route("api/message")]
        [HttpGet]
        public IEnumerable<Message> GetEncodedMessages()
        {
            var messages = ctx.Messages.ToList();
            var cipherDict = GetCiphers().ToDictionary(x => Convert.ToChar(x.OldChar), x => x.NewChar);
            var encodedMessages = new List<Message>();
            foreach (var message in messages)
            {
                var encodedText = new StringBuilder();
                foreach (var symbol in message.Text)
                {
                    var decodedSymbol = cipherDict.ContainsKey(symbol) ? cipherDict[symbol] : symbol.ToString();
                    encodedText.Append(decodedSymbol);
                }
                encodedMessages.Add(new Message
                {
                    MessageId = message.MessageId,
                    ReceiptTime = message.ReceiptTime,
                    Text = encodedText.ToString()
                });
            }

            return encodedMessages;
        }

        [Route("api/message/Create")]
        [HttpPut]
        public IHttpActionResult Create([FromBody]string text)
        {
            var message = new Message {ReceiptTime = DateTime.Now, Text = text};
            ctx.Messages.Add(message);
            ctx.SaveChanges();
            return Json("OK");
        }

        [Route("api/cipher")]
        [HttpGet]
        public IEnumerable<Cipher> GetCiphers()
        {
            return ctx.Ciphers.ToList();
        }
    }
}

CodeFirst/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CodeFirst.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

CodeFirst/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
 
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Hello Angular 5</title>
</head>
<body>
<app-root>Загрузка...</app-root>
    <script src="~/public/polyfills.js"></script>
    <script src="~/public/app.js"></script>
</body>
</html>

CodeFirst/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Cipher", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Cipher")</li>
                    <li>@Html.ActionLink("О программе", "About", "Cipher")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Cipher")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>